#!/bin/bash
#
###################
# Auhtor : Hariharan
# Date : 25/4/2025
#
# This Script Describes about node health
#
# Version V1
# #################

set -x #debug the file
set -e #exit the script if any error
set -o #pipefail


echo "print the disk space"
df -h


echo "print the process running and filter python process"
ps aux | grep python | awk -F" " '{print $3}'


echo "print the memory"
free -m


echo "print the CPU details"
nproc


echo "print the list of process running with CPU usage and Memory Usage"
top
